apiVersion: v1
kind: Namespace
metadata:
  name: utorrent

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ut-sc
  namespace: utorrent
provisioner: kubernetes.io/NFS
volumeBindingMode: WaitForFirstConsumer

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ut-pv
  namespace: utorrent
spec:
  storageClassName: ut-sc
  capacity:
    storage: 350Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/volume/utorrent"
    server: 192.168.0.7

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ut-pvc
  namespace: utorrent
spec:
  storageClassName: ut-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 350Gi

---

apiVersion: v1
kind: Service
metadata:
  namespace: utorrent
  name: utorrent
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "6881"
    port: 6881
    targetPort: 6881
  selector:
    app: utorrent
status:
  loadBalancer: {}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: utorrent
  name: utorrent
spec:
  replicas: 1
  selector:
      matchLabels:
        app: utorrent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: utorrent
    spec:
      containers:
      - env:
        - name: HOST_GID
          value: "1002"
        - name: HOST_UID
          value: "1002"
        image: yurilchuk/utorrent-kubernetes:latest
        name: utorrent
        ports:
        - containerPort: 8080
        - containerPort: 6881
        resources: {}
        volumeMounts:
        - mountPath: /utorrent/media
          name: utorrent
        - mountPath: /utorrent/settings
          name: utorrent
        #- mountPath: /settings/utserver.conf
        #  name: utorrent-claim2
      restartPolicy: Always
      securityContext:
        supplementalGroups: [65534]
      volumes:
      - name: utorrent
        persistentVolumeClaim:
          claimName: ut-pvc
     # - name: utorrent-claim2
     #   persistentVolumeClaim:
     #     claimName: utorrent-claim2
status: {}